### ISSUE TITLE
Build the code in win10 environment

### ISSUE THREAD

**Issue by royyy83512** [desowin/usbpcap#102]
Hi,

I am wondering how I can build the code in win10 environment, since the instruction only mentioned win7 and 8. I have downloaded Windows Driver Kit 7.1.0 but it seems unworkable.

Thanks.
RoyL

**Comment by desowin** [comment]
So far, all releases were built on Windows 7. To build on Windows 10, most likely #87 should be done.

**Comment by Kyu** [comment]
Any update on this? What would be the steps required to make this happen?
