### ISSUE TITLE
Not listing usb devices shared via network

### ISSUE THREAD

**Issue by realivanjx** [desowin/usbpcap#107]
Hi,

I have devices that are shared via network (with usb redirector technician edition). It works well with my programs with said device just like it is directly connected to my pc. But unfortunately usbpcap does not list it. Here are what it says:

```
Following filter control devices are available:
1 \\.\USBPcap1
  \??\USB#ROOT_HUB30#5&5b2d6c9&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}
    [Port 7] USB Input Device
      HID-compliant mouse
    [Port 8] USB Composite Device
      USB Input Device
        HID Keyboard Device
      USB Input Device
        HID Keyboard Device
        HID-compliant system controller
        HID-compliant consumer control device
        HID-compliant vendor-defined device
    [Port 12] Xbox One Controller
      USB Input Device
        XINPUT compatible HID device
2 \\.\USBPcap2
  \??\USB#ROOT_HUB30#5&1888fbf0&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}
3 \\.\USBPcap3
  \??\USB#ROOT_HUB30#5&ab90873&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}
Select filter to monitor (q to quit):
```

and with `-I`:

```
Hardware ID: USB\ROOT_HUB30&VID1022&PID15E1
Hardware ID: USB\ROOT_HUB30
Found standard HWID
Hardware ID: USB\ROOT_HUB30&VID1022&PID15E0&REV0000
Hardware ID: USB\ROOT_HUB30&VID1022&PID15E0
Hardware ID: USB\ROOT_HUB30
Found standard HWID
Hardware ID: USB\ROOT_HUB30&VID1022&PID43BC&REV0002
Hardware ID: USB\ROOT_HUB30&VID1022&PID43BC
Hardware ID: USB\ROOT_HUB30
Found standard HWID
```

Here is my device:
![Screenshot 2020-10-07 200003](https://user-images.githubusercontent.com/12814796/95334288-1dbfcf80-08d8-11eb-804b-cb83ff203653.jpg)

Any help is appreciated.
Thanks.

**Comment by realivanjx** [comment]
This also might be related to #97

**Comment by nefarius** [comment]
This is unfortunately "by design" and not fixable by USBPcap. These virtual USB emulation drivers don't emulate a host controller and a hub, they're basically bare-minimal bus drivers that just expose PDOs with USB device interfaces and handle URBs. Without a proper hub device object, USBPcap can not enumerate and load onto them, hence not being available for capture.

![image](https://user-images.githubusercontent.com/286631/169448164-159fcb7c-2ada-4525-95e9-95c6475b6c20.png)

**Comment by realivanjx** [comment]
im closing this as this is not the issue with usbpcap

**Comment by nefarius** [comment]
> im closing this as this is not the issue with usbpcap

Same case with #97 👌
