### ISSUE TITLE
Unknown type 7f

### ISSUE THREAD

**Issue by Ku100vEvgen** [desowin/usbpcap#132]
Hi !

1b 00 90 53 be 3f 8f c0 ff ff 00 00 00 00 2a 00
01 01 00 14 00 00 ff 00 00 00 00

parsed as
    URB transfer type: Unknown (0xff)
        [Expert Info (Error/Malformed): USBPcap did not recognize URB Function code (report to desowin.org/USBPcap)]
            [USBPcap did not recognize URB Function code (report to desowin.org/USBPcap)]

USBPcap 1.5.4.0

**Comment by desowin** [comment]
Duplicate of #78
