### ISSUE TITLE
USB port(s) not showing up after install, Win7Pro

### ISSUE THREAD

**Issue by Progman3K** [desowin/usbpcap#19]
Hi,

I installed usbpcap on my Windows machine and it DID function until I uninstalled it.

After re-installing/rebooting, the only ports that Wireshark lists as interfaces are the computer's network card and virtual (vitualbox) network card.

What can I do to get it working again?

Is there any log of why it is failing?

Once I install usbpcap it does not function but if I try re-installing it, it complains it must be uninstalled first, so I uninstall it and then reboot, boot up and install usbpcap but it still won't list the USB in the Wireshark interfaces.

Please advise
Thanks

**Comment by desowin** [comment]
Does USBPcapCMD list the USB devices?

**Comment by tallship** [comment]
I  believe this may be the bug report that has the fix for you here:
https://github.com/desowin/usbpcap/issues/3

**Comment by desowin** [comment]
Most likely this is fixed in 1.2.0.3. Please reopen if this is not the case.
