### ISSUE TITLE
Feature Suggestion: .pcap replay

### ISSUE THREAD

**Issue by CooperWhitlow** [desowin/usbpcap#24]
Not sure how difficult this would be. tcpreplay exists for TCP/IP .pcap files but nothing for sending USB captures.

**Comment by desowin** [comment]
Considering that USBPcapDriver is filter driver, I think the pcap replay is pretty much impossible to do. I think you could try to build such tool using libusb, but you'd have to install libusb driver instead of the currently used USB device driver.
