### ISSUE TITLE
DeviceIoControl Failed with  1 status

### ISSUE THREAD

**Issue by saranvs** [desowin/usbpcap#28]
I successfully build the Usbpcap Project, but during debugging I got the error Like this
" DeviceIoControl Failed with  1 status  (supplementary code -858993460)"
 " Thread Started with Invalid read handle!"

I can able to list my device, but can't able to open it or read from it. But the USBPcapSetup-1.0.0.7.exe from your website is working for me. I can able to list and read from the device.  Pls help me to solve this issue....

**Comment by desowin** [comment]
Error 1 is ERROR_INVALID_FUNCTION. Without any additional information about the issue, I am unable to help.
