### ISSUE TITLE
desowin.org is down

### ISSUE THREAD

**Issue by fstd** [desowin/usbpcap#33]
is there an alternative download mirror?

**Comment by desowin** [comment]
https://bintray.com/desowin/USBPcap
https://sourceforge.net/projects/usbpcap/?source=directory

Installer is also bundled with Wireshark.

**Comment by fstd** [comment]
On Tue, Nov 22, 2016 at 06:39:32AM -0800, Tomasz Moń wrote:
> https://bintray.com/desowin/USBPcap
> https://sourceforge.net/projects/usbpcap/?source=directory
Thanks!

> Installer is also bundled with Wireshark.
That one bails out telling me I need KB3033929, when the
KB3033929 installer tells me it's already present, duh :-).
That's how I came to be looking for an alternative source
in the first place.
This is Win7 Enterprise 64bit, in case it matters.

**Comment by desowin** [comment]
Added all releases to Github Releases. Website is now hosted on Github Pages.
