### ISSUE TITLE
BSOD due to USBPcap driver

### ISSUE THREAD

**Issue by shaharlux** [desowin/usbpcap#36]
Following WIN32 API code crashes (BSOD) the system. Tested on Microsoft Windows [Version 10.0.14393]. Easily reproduced:
WIN32_FILE_ATTRIBUTE_DATA FileData;
GetFileAttributesEx(L"\\\\.\\USBPcap1", GetFileExInfoStandard, &FileData))

**Comment by desowin** [comment]
Fixed in 1.2.0.1.
