### ISSUE TITLE
How to Redirect USBPcapCmd.exe "USB interfaces list" output to a text file.

### ISSUE THREAD

**Issue by pramodjnp** [desowin/usbpcap#37]
Hi i need to redirect interface list from USBPcapcmd.exe to an text file for getting USB HUB number in command line. please help me how to achieve this, is there any way, i can get "USB interface list" to a text file.

please any one help me

Thanks in Advance!!

**Comment by desowin** [comment]
If you would like a easily parsable string then please take a look at extcap interface specification: https://wiki.wireshark.org/Development/Extcap#Current_flow

USBPcapCMD implements extcap interface. Examples:
USBPcapCMD.exe --extcap-interfaces
USBPcapCMD.exe --extcap-interface \\.\USBPcap1 --extcap-config

**Comment by pramodjnp** [comment]
Hi thanks for the reply. Is there any way we can get **"interface"** with its connected **"USB Drives list"**.
As there in the below image.

![usbpcap_interface](https://cloud.githubusercontent.com/assets/29099779/26672926/a4393d64-46d8-11e7-830d-e6284f7229de.PNG)

Thanks in Advance!!!

**Comment by pramodjnp** [comment]
Hi desowin, 
Thanks for the reply, its working for me.
