### ISSUE TITLE
Windows 10 flagging unsigned driver

### ISSUE THREAD

**Issue by herrameise** [desowin/usbpcap#43]
The installer may be signed, but it looks like the actual driver is not. After installing USBPcap 1.2.0.1, Windows 10 displays a message that it has blocked the installation of an unsigned driver. On reboot, all of my USB devices no longer worked until I uninstalled the USBPcap program. This was not an issue with the older version of USBPcap that used to ship with Wireshark. However, the new Wireshark release (2.4.0) is bundled with USBPCap 1.2.0.1.

**Comment by herrameise** [comment]
just verified that the previous release (1.0.0.7) has no issues installing on Windows 10

**Comment by desowin** [comment]
I am pretty sure the driver is signed. It is standard Code Signing certificate however.

I am working on HLK submission which should solve the problem.

**Comment by jeremypoulter** [comment]
I also had this issue, is there any update?

**Comment by desowin** [comment]
Please report how USBPcap 1.2.0.2 behaves on your computer.

**Comment by jeremypoulter** [comment]
Sorry, I get the same;

![screenshot 2017-08-03 21 32 20](https://user-images.githubusercontent.com/6116992/28942517-8a7e0110-7893-11e7-85ba-1e17de49fee4.png)

**Comment by desowin** [comment]
Do you have Secure boot enabled? Did the USB devices work after restart?

The solution to this is attestation signing, but unfortunately I cannot do this alone, it needs to go through the company and there is paperwork burden.

**Comment by desowin** [comment]
Please let me know if 1.2.0.3 works for you.

**Comment by rogerdc** [comment]
I was able to successfully install it and my USB devices are still working.
