### ISSUE TITLE
How do I replay usbpcap file or each packet one by one?

### ISSUE THREAD

**Issue by vcidst** [desowin/usbpcap#46]
I have a pcap file generated by sniffing usb interaction with a hardware that I want to reverse engineer. How do I send exactly the same packets again to the device (replay packets) using either python (pyusb) or C?

[Here's a link to part of the data dump](https://gist.github.com/vcidst/c63e289dc223c9018c9e634934092dd5) that contains 20 packets

**Comment by desowin** [comment]
The linked data dump is not generated by USBPcap. Based on that dump, it is impossible to tell to which endpoint the data was being directed. PipeHandle	0xffffe3884a84d7d8 can really mean any endpoint of the device.

USBPcap does keep track of pipe handles when they are opened and uses that information to fill USBPcap pseudoheader with the actual endpoint information.

Once you know the endpoint, you simply read or write data to the endpoint using the bulk transfer (all transfers in the linked dump are bulk transfers).
