### ISSUE TITLE
wireshark problem

### ISSUE THREAD

**Issue by ArsalanAbid** [desowin/usbpcap#49]
i installed wireshark 64 bit windows 7 home basic and it shows msvcp120.dll file missing ...i tried other version of wireshark so it was showing some other .dll file missing...tried every website but couldn`t get that dll file .they ask money to register ..i want in free...any solution??

**Comment by WildCard65** [comment]
You need to install a Visual C++ redistributable package that Microsoft provide free of charge, the version I believe you need is for Visual C++ 2013

**Comment by desowin** [comment]
Like @WildCard65 mentioned, the msvcp120.dll is part of Visual C++ Redistributable Packages for Visual Studio 2013
