### ISSUE TITLE
"Couldn't open device 2" message

### ISSUE THREAD

**Issue by Francisco-Javier-Quiros-git** [desowin/usbpcap#5]
I get the message "Couldn't open device 2" when I run usbpcap with the first
available filter.

Since when I run usbpcap with no arguments the program continuously scrolls
blank lines I redirected the output to a file and examined the file with the eclipse
text editor. Eclipse presents the output with a space between each printable
character (see attached image below) which could mean that the characters are 16 bit wide characters. Could this indicate a problem with your use of CreateFileA and CreateFile in usbpcap?

![filter](https://f.cloud.github.com/assets/5768287/1402755/5d160400-3ce9-11e3-8ab8-5d8c27f8211f.PNG)

**Comment by desowin** [comment]
I believe the problem is obsolete with recent UBSPcap release. If it is not, please open new issue.
