### ISSUE TITLE
Does USBPcapCMD.exe need admin rights/privileges to perform USB packet capture

### ISSUE THREAD

**Issue by kirankumarg81** [desowin/usbpcap#56]
Would like to know if USBPcapCMD.exe need admin rights/privileges to perform USB capture.
Platform: Windows-7
USBPcap version: 1.2.0.3

It is installed by Admin and executed by user in my case. Let me know if admin need to set any permissions on USBPcapCMD.exe file.

Thank you.

**Comment by desowin** [comment]
The actual capture needs Elevated priviledges. There's no need to set any special permissions on the USBPcapCMD - if you start capture from unelevated USBPcapCMD, it'll automatically display the UAC elevation dialog.

The only reason for the admin rights is to prevent malicious use of the USBPcapDriver (eg. to prevent unelevated viruses from capturing the USB traffic).

**Comment by desowin** [comment]
If you run USBPcapCMD as non-admin user, the UAC screen will ask for admin username and password.

**Comment by desowin** [comment]
Closing this as this is basic security precaution to require admin rights for capturing on USB devices (USB keyboards are really common nowadays).

**Comment by kirankumarg81** [comment]
Thanks for the reply, it was very useful.
