### ISSUE TITLE
Virtual Com port capture shows up as ethernet II and is greyed out.

### ISSUE THREAD

**Issue by villad2-mdt** [desowin/usbpcap#94]
I have been using USBPcap to capture USB traffic for a virtual com port that is interfaced to an NXP development board. When I capture the data the info field says it is ethernet II and the line is greyed out, other then that it appears to be working fine. I don't think this is correct, but I am not that knowledgeable about USB communications. I Wireshark Version 3.0.7 (v3.0.7-0-g9435717b91f5) and the latest version of USBPcap 1.5.3.0.

**Comment by desowin** [comment]
I believe you are talking about Wireshark bug [14587](https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=14587)
